### ISSUE TITLE
Plugin v0.0.7 doesn't activate

### ISSUE THREAD

**Issue by fu-raz** [fu-raz/midi-mixer-wavelink-new#2]
Hello,
I would like try you plugin with my DIY streamDeck.
I Downloaded your folder and I put here %appdata%\midi-mixer-app\plugins
I see your plugin but when I click on activate, nothing happens and it stays in deactivated (the button does not change to activated)
Thank you for your help, maybe I can help you later

_Originally posted by @DrMicka in https://github.com/fu-raz/midi-mixer-wavelink-new/issues/1#issuecomment-1334028725_

**Comment by fu-raz** [comment]
It's best to use the compiled version of the plugin. You can find it on the releases page here: https://github.com/fu-raz/midi-mixer-wavelink-new/releases

**Comment by fu-raz** [comment]
If you want to do it your way, you will have to go into the folder with a command prompt and run `npm install` first. If you download the compiled version, you can just double click it and it will automatically install everything needed.

**Comment by DrMicka** [comment]
Thank you very much for your answer and really sorry for my stupid question, I know you have to look in the release....
So I tried to install the plugin with version 0.0.7 but it doesn't work, no file in the plugin folder, just opening the midi mixer.
I tried with version 0.0.6 and it's OK.
Maybe a compilation problem when you created version 0.0.7 :)

**Comment by fu-raz** [comment]
Don't worry about it! I'm glad you got 0.0.6 running. I'll go check what's the problem with 0.0.7. You might be right about the compilation problem

**Comment by fu-raz** [comment]
I just tested my version 0.0.7 and for me it works. Could you try to enable Dev mode and see if you get an error on 0.0.7?
![image](https://user-images.githubusercontent.com/5355154/205267083-6e0c607e-8d5c-4d1e-9c1c-f24543f35e87.png)

**Comment by DrMicka** [comment]
After different tests, I understand why I couldn't install version 0.0.7.
To install the plugin, it is mandatory to have the midi mixer software open. I don't know why
Thanks a lot, I tested and for my stream deck DIY, it is possible to use the buttons and faders to control the volume of the wave link :)

**Comment by fu-raz** [comment]
That's good to hear! If you have any suggestions, let me know :)
