### ISSUE TITLE
not working properly with wave link 1.8

### ISSUE THREAD

**Issue by ChotaFallen** [fu-raz/midi-mixer-wavelink-new#4]
Hello,

I try to install you software. Thank you for your work.
I use wave link 1.8.2.730  with  midimixer and have some issues

1. the sliders in wave link are not responding 
2. there is no stream or monitor output to use only normal like game or browser can choosed in midi mixer

where in which folder is the plugin installed?
Thank you

**Comment by fu-raz** [comment]
I'm using it on 1.8.2.730 myself. You should download the .midiMixerPlugin file from the releases page and double click it to install.
https://github.com/fu-raz/midi-mixer-wavelink-new/releases/tag/v0.0.15

Then make sure you have enabled the plugin and you see the new mixers:
![image](https://github.com/fu-raz/midi-mixer-wavelink-new/assets/5355154/2ed48163-ec1a-440d-9f35-2337dc8a150b)

**Comment by fu-raz** [comment]
WaveLink is at version 1.9 now and everything still seems to be working. I'm closing this issue, but if you run into problems again, let me know.
