### ISSUE TITLE
Mute button for stream and monitor separately

### ISSUE THREAD

**Issue by fu-raz** [fu-raz/midi-mixer-wavelink-new#5]
a suggestion, and perhaps it is already possible to implement by making a custom profile? That is, using for example the S button to mute the rotory control. now, you can only mute the sliders. 

this way, it would be possible to have slider be monitor output, and you could use rotory over for stream. then mute slider with M and rotory with S.  Though, this is probably not something most people would need - but wonder if it is technically possible.

_Originally posted by @mornja in https://github.com/fu-raz/midi-mixer-wavelink-new/issues/1#issuecomment-1339506493_

**Comment by fu-raz** [comment]
Done in v0.9.0

**Comment by ItsMeAndeh** [comment]
> Done in v0.9.0

Is there some instructions regarding this feature..? It's totally what I was looking for but when I try to re-assign any S button to "Toggle Mute: "GROUP" Stream" it appears the S buttons will mute correctly but not unmute and also do not enable their respective indicators like the M buttons do when muting.

I'm very inexperienced with both MIDI Mixer and this plugin so it's very likely I'm doing something incorrect and removing the S controls and indicators from the pre-made groups are not the way to make this change..?

Thank you for any suggestions.
